language: go

go:
  - "1.13.x"

branches:
  only:
    - master
    - develop

# https://docs.travis-ci.com/user/database-setup/
services:
  - mysql
  - redis-server

env:
  - GO111MODULE=on

install:
  - cd /usr/bin
  - go get -u github.com/mgechev/revive
  - cd -

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS todo;'
  - find . -name "*.go" | xargs gofmt -w
  - git diff --exit-code
  - revive -config=scripts/revive.toml -formatter friendly ./...

script:
  - go test ./... || exit 0
  - go test ./... -coverprofile=coverage.txt -covermode=atomic || exit 0

after_success:
  - bash <(curl -s https://codecov.io/bash)