[db]
    [db.mysql]
    host="127.0.0.1"
    port=3306
    username="root"
    password="123456"
    db="todo"
    [db.redis]
    host="127.0.0.1"
    port=6379
[server]
host="127.0.0.1"
port=7410
wxloginurl="https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"
appid=""
secret=""
groupcodesecret=""
secretkey=""
