[db]
    [db.mysql]
    host="127.0.0.1"
    port=3306
    username="root"
    password="123456"
    db="todo"
    [db.redis]
    host="127.0.0.1"
    port=6379
[server]
port=7410
appid="wx8b3637af0295daed"
secret="4be82d4abae4522e8ef1990e91a67a20"
